### ISSUE TITLE
进不去系统

### ISSUE THREAD

**Issue by nearnight21** [hysro1997/school-score#1]
前后端环境配置完成,数据库sql文件也已经加载
尝试了admin/123456不正确.
在readme里也没有看到, 麻烦作者大大解答

**Comment by nearnight21** [comment]
好的进去了, 但是为什么是若依原版的内容.

**Comment by hysro1997** [comment]
用最新的项目看看，又做了大的修改，有问题可以加QQ联系。

**Comment by hysro1997** [comment]
QQ群：637914590
